name: dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - cookiecutter
  - jupyter
  - jupyterlab
  - scikit-learn
  - pandas
  - plotly
  - matplotlib
  - pip:
    - --editable .